export const mockArticlesResponse = {
  statusCode: 200,
  body: {
    data: [{
      id: 1,
      title: 'dummy title',
      slug: 'dummy-slug',
      status: 'publish',
      post_type: 'addon-introductio',
      contents: {
        author: null,
        link: 'https://128na.github.io/iss',
        description: null,
        license: null,
        thanks: null,
        thumbnail: null,
      },
      categories: [],
      tags: [],
      created_at: '2022-01-02T03:04:05',
      published_at: '2022-02-03T04:05:06',
      modified_at: '2022-03-04T05:06:07',
      url: 'http://localhost:8080/articles/dummy-slug',
      metrics: {
        totalViewCount: 1,
        totalConversionCount: 2,
        totalRetweetCount: 3,
        totalReplyCount: 4,
        totalLikeCount: 5,
        totalQuoteCount: 6,
        totalImpressionCount: 7,
        totalUrlLinkClicks: 8,
        totalUserProfileClicks: 9,
      },
    }],
  },
};
