@startuml erd
title 依存関係
object User
object Profile
object ProfileData
object Article
object Content
object AddonPostContent
object AddonIntroductionContent
object MarkdownContent
object PageContent
object Sections
object Section
object SectionCaption
object SectionText
object SectionImage
object SectionUrl
object Attachment
object Category
object Tag
object PakAddonCount
object UserAddonCount
object Redirect
object CompressedImage
object ViewCount
object ConversionCount
object PostTypes
object Statuses

object ArticleAnalyticsService
object ArticleEditorService
object ArticleService
object AttachmentService
object CategoryService
object TagService
object UserService
object SitemapService
object RedirectService
object PresentationService
object FeedService
object CheckDeadLinkService
object CompressImageService

User -- Profile
User -- Attachment:myAttachments
User -- "n" Article
Profile -- ProfileData
Profile -- Attachment

Article -- Content
Article -- Attachment
Article -- "n" Tag
Article -- "n" Category
Article -- "n" ViewCount
Article -- "n" ConversionCount
Article -- PostTypes
Article -- Statuses

Content <|-- AddonPostContent
Content <|-- AddonIntroductionContent
Content <|-- MarkdownContent
Content <|-- PageContent
PageContent -- Sections
Sections -- "n" Section
Section <|-- SectionCaption
Section <|-- SectionText
Section <|-- SectionImage
Section <|-- SectionUrl

PakAddonCount -- Category
PakAddonCount -- Article
UserAddonCount -- User
UserAddonCount -- Article

CompressImageService -- Attachment
CompressImageService -- CompressedImage
CheckDeadLinkService -- Article
FeedService -- Article
PresentationService -- PakAddonCount
PresentationService -- UserAddonCount
RedirectService -- Redirect
SitemapService -- Article
SitemapService -- PakAddonCount
SitemapService -- UserAddonCount
UserService -- User

ArticleAnalyticsService -- Article
ArticleEditorService -- Article
ArticleEditorService -- Category
ArticleEditorService -- Tag
ArticleEditorService -- User
ArticleEditorService -- PostTypes
ArticleEditorService -- Statuses
ArticleService -- Article
ArticleService -- Category
ArticleService -- Tag
ArticleService -- User
AttachmentService -- Attachment
AttachmentService -- User
AttachmentService -- Article
CategoryService -- Category
TagService -- Tag

@enduml
